In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
df=pd.read_csv('airplane_price_dataset.csv')
df

,Model,Üretim Yılı,Motor Sayısı,Motor Türü,Kapasite,Menzil (km),Yakıt Tüketimi (L/saat),Saatlik Bakım Maliyeti ($),Yaş,Satış Bölgesi,Fiyat ($)
0,Bombardier CRJ200,1987,2,Turbofan,50,3000,14.36,2185.43,36,Asya,1.285708e+07
1,Bombardier CRJ200,1997,2,Turbofan,50,3000,4.03,1202.08,26,Avrupa,1.391406e+07
2,Airbus A320,1988,2,Turbofan,180,6300,13.26,761.38,35,Avustralya,9.073570e+07
3,Boeing 737,2023,2,Turbofan,162,5700,14.61,592.63,0,Avustralya,1.366597e+08
4,Cessna 172,1985,1,Piston,4,1285,18.49,4245.99,38,Güney Amerika,2.037981e+05
...,...,...,...,...,...,...,...,...,...,...,...
12372,Boeing 777,1994,2,Turbofan,396,15600,12.16,3054.29,29,Avrupa,3.898071e+08
12373,Bombardier CRJ200,2005,2,Turbofan,50,3000,8.26,3107.67,18,Afrika,1.593888e+07
12374,Boeing 737,2015,2,Turbofan,162,5700,6.93,3972.16,8,Kuzey Amerika,9.870994e+07
12375,Cessna 172,2013,1,Piston,4,1285,14.28,999.84,10,Afrika,3.965207e+05
12376,Bombardier CRJ200,2013,2,Turbofan,50,3000,2.42,1035.75,10,Avustralya,2.320782e+07